In [1]:
import sympy as sp
import numpy as np

In [2]:
def fonctionf(x,y):
    f = (x+2*y-7)**2+(2*x+y-5)**2
    return f

In [3]:
def deriv(x,y):
    a, b = sp.symbols('a b',real =True)
    fx = sp.diff(fonctionf(a,b),a).subs(a,x).subs(b,y)
    fy = sp.diff(fonctionf(a,b),b).subs(a,x).subs(b,y)
    return fx,fy

In [4]:
def gradient_pas_rebroussement(n,eps): 
    alpha , beta = 0.5 , 0.9 
    x, y = 0,0  # point initial (0, 0)
    liste_x = np.zeros(n+1)                #Une liste qui stocke les coordonnées de l’axe X
    liste_y = np.zeros(n+1)                #Une liste qui stocke les coordonnées de l’axe Y
    liste_h = np.zeros(n+1)                #Une liste qui stocke les coordonnées de l’axe Z
    liste_crit = np.zeros(n+1)             #Une liste qui stocke les valeurs de critères
    h= fonctionf(x,y)
    liste_h[0] = h
    
    liste_x[0] = x
    liste_y[0] = y
    crit = ((deriv(x,y)[0])**2+(deriv(x,y)[1])**2)**0.5     
    liste_crit[0] = crit
    
    deriv_x, deriv_y = deriv(x, y)
    m = 0                                 #Le nombre initial d’étapes est de 0
    i = 1                                 #L'exponentielle initial de beta est 1
    # Condition de résiliation
    while m < n and crit > eps :
        deriv_x, deriv_y = deriv(x, y)
        x = x - alpha*beta**i*deriv_x
        y = y - alpha*beta**i*deriv_y
        h= fonctionf(x,y)
        #print(h)
        if h<=liste_h[m]:                #Assurer que le point suivant doit être plus petit en hauteur
            m+=1                         #Décider de prendre cette étape, la valeur m représentant le nombre d’étapes est augmentée de 1
            liste_x[m] = x               #Si la condition est remplie, cette valeur x est stockée
            liste_y[m] = y               #Si la condition est remplie, cette valeur y est stockée
            h= fonctionf(x,y)
            liste_h[m] = h               #Si la condition est remplie, cette valeur h est stockée
            crit = ((deriv(x,y)[0])**2+(deriv(x,y)[1])**2)**0.5
            liste_crit[m] = crit         #Si la condition est remplie, cette valeur de critères est stockée
            i=1                          #Après cette étape, l'exponentielle de beta est réécrit comme 1

        else:
            i+=1                        #Si la hauteur ne diminue pas, augmentez la taille exponentielle du beta
        
    return liste_x,liste_y,liste_crit,liste_h, m

In [7]:
N=50
eps=0.1
gradient_pas_rebroussement(N,eps)

(array([ 0.        , -0.54878239, -0.19936759,  0.07121869,  0.28075869,
         0.4430249 ,  0.56868264,  0.66599106,  0.74134597,  0.79970025,
         0.84488937,  0.87988349,  0.90698267,  0.92796807,  0.94421901,
         0.95680362,  0.96654905,  0.97409583,  0.97994001,  0.98446569,
         0.98797035,  0.99068433,  0.99278601,  0.99441354,  0.99567389,
         0.99664989,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]),
 array([0.        , 1.45121226, 1.80063241, 2.07121869, 2.28075869,
        2.4430249 , 2.56868264, 2.66599106, 2.74134597, 2.79970025,
        2.84488937, 2.87988349, 2.90698267, 2.92796807, 2.94421901,
        2.95680362, 2.96654905, 2.97409583,

In [8]:
N=50
eps=0.01
gradient_pas_rebroussement(N,eps)

(array([ 0.        , -0.54878239, -0.19936759,  0.07121869,  0.28075869,
         0.4430249 ,  0.56868264,  0.66599106,  0.74134597,  0.79970025,
         0.84488937,  0.87988349,  0.90698267,  0.92796807,  0.94421901,
         0.95680362,  0.96654905,  0.97409583,  0.97994001,  0.98446569,
         0.98797035,  0.99068433,  0.99278601,  0.99441354,  0.99567389,
         0.99664989,  0.9974057 ,  0.99799099,  0.99844424,  0.99879523,
         0.99906704,  0.99927752,  0.99944052,  0.99956674,  0.99966449,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]),
 array([0.        , 1.45121226, 1.80063241, 2.07121869, 2.28075869,
        2.4430249 , 2.56868264, 2.66599106, 2.74134597, 2.79970025,
        2.84488937, 2.87988349, 2.90698267, 2.92796807, 2.94421901,
        2.95680362, 2.96654905, 2.97409583,

### Plus le $\epsilon$ est petit , plus la convergence est précise et plus le $\epsilon$ est petit, plus le nombre d’étapes de convergence est élevé

In [10]:
tabx, taby,tabh, tabcrit, m = gradient_pas_rebroussement(50,0.1)
if tabcrit[m] < eps :
    print('La méthode converge en', m, 'pas')
else :
    print('La méthode ne converge pas en', N, 'pas')

La méthode converge en 25 pas


In [11]:
tabx, taby,tabh, tabcrit, m = gradient_pas_rebroussement(50,0.01)    #le changement du valeur de epsilon
if tabcrit[m] < eps :
    print('La méthode converge en', m, 'pas')
else :
    print('La méthode ne converge pas en', N, 'pas')

La méthode converge en 34 pas


### Le nombre d’étapes convergentes est également affecté par $\epsilon$.

## Si on change le choix du ( $\alpha$ ,  $\beta$ )

###  Nous avons déterminé tous les autres coefficients, ne laissant que l’alpha et le beta comme variables.

In [12]:
def gradient_pas_rebroussement1(alpha,beta): 
    n=50
    eps=0.01
    x, y = 0,0  # point initial (0, 0)                   
    liste_x = np.zeros(n+1)
    liste_y = np.zeros(n+1)
    liste_h = np.zeros(n+1)
    liste_crit = np.zeros(n+1)
    h= fonctionf(x,y)
    liste_h[0] = h
    
    liste_x[0] = x
    liste_y[0] = y
    crit = ((deriv(x,y)[0])**2+(deriv(x,y)[1])**2)**0.5
    liste_crit[0] = crit
    
    deriv_x, deriv_y = deriv(x, y)
    m = 0
    i = 1
    # Condition de résiliation
    while m < n and crit > eps :
        deriv_x, deriv_y = deriv(x, y)
        x = x - alpha*beta**i*deriv_x
        y = y - alpha*beta**i*deriv_y
        h= fonctionf(x,y)
        if h<=liste_h[m]:
            m+=1
            liste_x[m] = x
            liste_y[m] = y
            h= fonctionf(x,y)
            liste_h[m] = h
            crit = ((deriv(x,y)[0])**2+(deriv(x,y)[1])**2)**0.5
            liste_crit[m] = crit
            i=1

        else:
            i+=1
        
    return liste_x,liste_y,liste_crit,liste_h, m

In [13]:
i=0
j=0
M=[]
for i in range (1,8):                            #Modifier les valeurs alpha et beta pour comparer le nombre final d’étapes convergentes
    alpha=i/10
    for j in range(1,10):
        beta=j/10
        m=0
        tabx, taby,tabh, tabcrit, m = gradient_pas_rebroussement1(alpha,beta)
        if tabcrit[m] < eps :
            print('La méthode converge en', m, 'pas')        #Le nombre d’étapes convergentes
            print(i/10,j/10)                                 #Valeurs alpha et beta pour chaque étape convergente
        M.append(m)

La méthode converge en 50 pas
0.1 0.3
La méthode converge en 50 pas
0.1 0.4
La méthode converge en 50 pas
0.1 0.5
La méthode converge en 45 pas
0.1 0.6
La méthode converge en 38 pas
0.1 0.7
La méthode converge en 33 pas
0.1 0.8
La méthode converge en 29 pas
0.1 0.9
La méthode converge en 50 pas
0.2 0.2
La méthode converge en 45 pas
0.2 0.3
La méthode converge en 33 pas
0.2 0.4
La méthode converge en 39 pas
0.2 0.5
La méthode converge en 20 pas
0.2 0.6
La méthode converge en 12 pas
0.2 0.7
La méthode converge en 10 pas
0.2 0.9
La méthode converge en 50 pas
0.3 0.1
La méthode converge en 45 pas
0.3 0.2
La méthode converge en 29 pas
0.3 0.3
La méthode converge en 20 pas
0.3 0.4
La méthode converge en 17 pas
0.3 0.5
La méthode converge en 9 pas
0.3 0.6
La méthode converge en 5 pas
0.3 0.7
La méthode converge en 29 pas
0.3 0.8
La méthode converge en 2 pas
0.3 0.9
La méthode converge en 50 pas
0.4 0.1
La méthode converge en 33 pas
0.4 0.2
La méthode converge en 23 pas
0.4 0.3
La méthode conv

### Si ($\alpha$ , $\beta$) =(0.3,0.9), le nombre d'étapes de convergence est le plus faible , m =2 . Moins il y a d'étapes de convergence, plus la convergence est rapide.

## Si on change le choix du point initial

###  Nous avons déterminé tous les autres coefficients, ne laissant que le point initial comme variables.

In [19]:
def gradient_pas_rebroussement2(x,y): 
    n=50
    eps=0.01
    alpha = 0.3
    beta = 0.9
    liste_x = np.zeros(n+1)
    liste_y = np.zeros(n+1)
    liste_h = np.zeros(n+1)
    liste_crit = np.zeros(n+1)
    h= fonctionf(x,y)
    liste_h[0] = h
    
    liste_x[0] = x
    liste_y[0] = y
    crit = ((deriv(x,y)[0])**2+(deriv(x,y)[1])**2)**0.5
    liste_crit[0] = crit
    
    deriv_x, deriv_y = deriv(x, y)
    m = 0
    i = 1
    # Condition de résiliation
    while m < n and crit > eps :
        deriv_x, deriv_y = deriv(x, y)
        x = x - alpha*beta**i*deriv_x
        y = y - alpha*beta**i*deriv_y
        h= fonctionf(x,y)
        #print(h)
        if h<=liste_h[m]:
            m+=1
            liste_x[m] = x
            liste_y[m] = y
            h= fonctionf(x,y)
            liste_h[m] = h
            crit = ((deriv(x,y)[0])**2+(deriv(x,y)[1])**2)**0.5
            liste_crit[m] = crit
            i=1

        else:
            i+=1
        
    return liste_x,liste_y,liste_crit,liste_h, m

In [23]:
gradient_pas_rebroussement2(1,2)            #point initial (1,2)

(array([1.        , 1.00127876, 1.00000791, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]),
 array([2.        , 2.99690614, 2.99998879, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [21]:
gradient_pas_rebroussement2(5.8,9)         #point initial (5.8,9)

(array([5.8       , 1.00717795, 1.00000632, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]),
 array([9.        , 3.01242509, 3.00002926, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [22]:
gradient_pas_rebroussement2(1000,1000)            #point initial(1000,1000)

(array([1000.        ,    2.81583907,    1.00330711,    1.00000605,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ]),
 array([1000.        ,    4.80709384,    3.00326887,    3.00000588,
           0.        ,    0.        ,    0.        ,    0.   

### Quelle que soit la façon dont vous modifiez le point initial, il finira par converger vers le point (1,3) , indiquant qu’il s’agit du minimum global.
### Le choix du point initial affecte le nombre d’étapes de convergence, et plus on s’éloigne du point (1,3) , plus le nombre d’étapes de convergence est élevé, mais cet effet est relativement faible comparé avec le changement de ($\alpha$ , $\beta$).